### ISSUE TITLE
wrong files from composer

### ISSUE THREAD

**Issue by brianally** [Jeroen-G/laravel-pages#4]
I'm not sure how to explain this. I ran:
```sh
composer require jeroen-g/laravel-pages
```
That gave an error because of the dependency on cocur/slugify@master-dev
I then added that package as a dependency and ran the above again. My composer.json now has "jeroen-g/laravel-pages": "^2.0", but the files themselves do not reflect the latest changes in master. Specifically, the changes made to fix bugs #1 & #2.

I don't know enough about composer to say for sure but it seems like this package is not in sync with it. (I did not have an old version cached locally.)

However, as i said, my composer.json now claims that i have 2.0 installed. Go figure.

When i cloned the repo directly, of course, all was fine.

I forgot to note the version of composer itself (work machine) but i'm pretty sure it's up to date. I can let you know monday.

**Comment by Jeroen-G** [comment]
Which version of Laravel?

**Comment by brianally** [comment]
5.4 and PHP 7.1

**Comment by Jeroen-G** [comment]
Could you test with `"jeroen-g/laravel-pages": "dev-master"`?
If it works (it should, the tests pass), I'll make a new release.

**Comment by brianally** [comment]
That worked. Files up to date.

**Comment by Jeroen-G** [comment]
Tagged as version 3.0
